name: Nix on Linux

on:
  push:
    branches:
      - main
  pull_request:

permissions: read-all

jobs:
  nix:
    runs-on: ubuntu-latest
    name: nix-build
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b
        with:
          fetch-depth: 0
      - uses: cachix/install-nix-action@daddc62a2e67d1decb56e028c9fa68344b9b7c2a
        with:
          extra_nix_config: |
            experimental-features = nix-command flakes
      - run: nix flake check --print-build-logs --show-trace
